# config/packages/security.yaml
security:
    providers:
        in_memory:
            memory:
                users:
                    admin:
                        password: admin
                        roles: 'ROLE_ADMIN'
        our_db_provider:
            entity:
                class: App\Entity\Usuarios
                property: login
        chain_provider:
            chain:
                providers: [ in_memory, our_db_provider ]

    encoders:
        App\Entity\Usuarios:
            algorithm: bcrypt
        Symfony\Component\Security\Core\User\User: plaintext

    firewalls:
        main:
            provider: chain_provider
            #pattern: ^/
            anonymous: ~
            #http_basic: ~
            form_login:
                login_path: /admin/login
                check_path: /admin/login
            logout:
                path: /logout
                target: /

    access_control:
        - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
       # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
