<?php declare(strict_types = 1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
class Version20181105130628 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mssql', 'Migration can only be executed safely on \'mssql\'.');

        $this->addSql('CREATE TABLE clube (id INT IDENTITY NOT NULL, clubes_id INT, name NVARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_516984724E97A68B ON clube (clubes_id)');
        $this->addSql('CREATE TABLE pessoa (id INT IDENTITY NOT NULL, jogadores_id INT, name NVARCHAR(255) NOT NULL, discr NVARCHAR(255) NOT NULL, posicao NVARCHAR(255), PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1CDFAB82DC527FFC ON pessoa (jogadores_id)');
        $this->addSql('CREATE TABLE liga (id INT IDENTITY NOT NULL, name NVARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE clube ADD CONSTRAINT FK_516984724E97A68B FOREIGN KEY (clubes_id) REFERENCES liga (id)');
        $this->addSql('ALTER TABLE pessoa ADD CONSTRAINT FK_1CDFAB82DC527FFC FOREIGN KEY (jogadores_id) REFERENCES clube (id)');
        $this->addSql('DROP TABLE K_NOTAITENS');
        $this->addSql('DROP TABLE K_PD_USUARIOS');
        $this->addSql('DROP TABLE K_PRODUCAODOCS');
        $this->addSql('DROP TABLE K_PRODUCAOETAPAS');
        $this->addSql('DROP TABLE K_PRODUCAOITENS');
        $this->addSql('DROP TABLE K_PRODUCAOTERMINAL');
        $this->addSql('DROP TABLE K_USUARIOSNIVEIS');
    }

    public function down(Schema $schema)
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mssql', 'Migration can only be executed safely on \'mssql\'.');

        $this->addSql('CREATE SCHEMA db_accessadmin');
        $this->addSql('CREATE SCHEMA db_backupoperator');
        $this->addSql('CREATE SCHEMA db_datareader');
        $this->addSql('CREATE SCHEMA db_datawriter');
        $this->addSql('CREATE SCHEMA db_ddladmin');
        $this->addSql('CREATE SCHEMA db_denydatareader');
        $this->addSql('CREATE SCHEMA db_denydatawriter');
        $this->addSql('CREATE SCHEMA db_owner');
        $this->addSql('CREATE SCHEMA db_securityadmin');
        $this->addSql('CREATE SCHEMA dbo');
        $this->addSql('ALTER TABLE pessoa DROP CONSTRAINT FK_1CDFAB82DC527FFC');
        $this->addSql('ALTER TABLE clube DROP CONSTRAINT FK_516984724E97A68B');
        $this->addSql('CREATE TABLE K_NOTAITENS (DATAAUT DATETIME2(6), DATASYNC DATETIME2(6), HANDLE INT NOT NULL, NOTA INT, TABELAPRECO INT, PRODUTO INT, NOMEPRODUTO NVARCHAR(50) COLLATE Latin1_General_CI_AS, UNIDADE NVARCHAR(3) COLLATE Latin1_General_CI_AS, QUANTIDADE DOUBLE PRECISION, MEDIDA_X DOUBLE PRECISION, MEDIDA_Z DOUBLE PRECISION, MEDIDA_T DOUBLE PRECISION, MEDIDA_Y DOUBLE PRECISION, PESO DOUBLE PRECISION, EMENDA NCHAR(2) COLLATE Latin1_General_CI_AS, DATAENTREGA DATETIME2(6), VALORUNITARIO DOUBLE PRECISION, VALORDESCONTO DOUBLE PRECISION, VALORIPI DOUBLE PRECISION, VALORBCIPI DOUBLE PRECISION, VALORTOTAL DOUBLE PRECISION, VALORFRETE DOUBLE PRECISION, VALORICMS DOUBLE PRECISION, VALORBCICMS DOUBLE PRECISION, VALORICMSST DOUBLE PRECISION, VALORBCICMSST DOUBLE PRECISION, VALORPIS DOUBLE PRECISION, VALORBCPIS DOUBLE PRECISION, VALORCOFINS DOUBLE PRECISION, VALORBCCOFINS DOUBLE PRECISION, VALORCOFINSST DOUBLE PRECISION, VALORISSQN DOUBLE PRECISION, VALORBCISSQN DOUBLE PRECISION, PERCDESCONTO DOUBLE PRECISION, PERCIPI DOUBLE PRECISION, PERCICMS DOUBLE PRECISION, PERCICMSST DOUBLE PRECISION, PERCPIS DOUBLE PRECISION, PERCCOFINS DOUBLE PRECISION, PERCCOFINSST DOUBLE PRECISION, PERCISSQN DOUBLE PRECISION, PRECOTABELA DOUBLE PRECISION, TIPOOPERACAO INT, NCM NVARCHAR(25) COLLATE Latin1_General_CI_AS, CST NVARCHAR(10) COLLATE Latin1_General_CI_AS, CFOP NVARCHAR(10) COLLATE Latin1_General_CI_AS, CSOSN NVARCHAR(3) COLLATE Latin1_General_CI_AS, QTDENTREGUE INT, QTDBAIXADA INT, ENDERECO INT, ENDERECODESTINO INT, LOTE INT, NUMPROJETO NCHAR(2) COLLATE Latin1_General_CI_AS, ARQUIVO NVARCHAR(250) COLLATE Latin1_General_CI_AS, SERVICO INT, PRIMARY KEY (HANDLE))');
        $this->addSql('CREATE TABLE K_PD_USUARIOS (DATAAUT DATETIME2(6), DATASYNC DATETIME2(6), HANDLE INT NOT NULL, Z_GRUPO INT, NOME NVARCHAR(50) COLLATE Latin1_General_CI_AS, APELIDO NVARCHAR(250) COLLATE Latin1_General_CI_AS, SENHA NVARCHAR(250) COLLATE Latin1_General_CI_AS, CNPJCPF NVARCHAR(19) COLLATE Latin1_General_CI_AS, DATAULTIMOLOGIN DATETIME2(6), CLIENTE INT, NIVEL INT, COMISSAOVENDA DOUBLE PRECISION, PAGAMENTOEMISSAO DOUBLE PRECISION, PAGAMENTORECEBIMENTO DOUBLE PRECISION, VENCIMENTO INT, GRUPO INT, TERMINAL INT, IMAGEM NVARCHAR(250) COLLATE Latin1_General_CI_AS, EQUIPE INT, EMAIL NVARCHAR(250) COLLATE Latin1_General_CI_AS, REGIAO INT, PRIMARY KEY (HANDLE))');
        $this->addSql('CREATE TABLE K_PRODUCAODOCS (HANDLE INT NOT NULL, URL NVARCHAR(50) COLLATE Latin1_General_CI_AS, DATAAUT DATETIME2(6), DATASYNC DATETIME2(6), NOME NVARCHAR(10) COLLATE Latin1_General_CI_AS, ITEM INT, OBSERVACAO NVARCHAR(250) COLLATE Latin1_General_CI_AS, PRIMARY KEY (HANDLE))');
        $this->addSql('CREATE TABLE K_PRODUCAOETAPAS (HANDLE INT NOT NULL, NOME NVARCHAR(50) COLLATE Latin1_General_CI_AS, DATAAUT DATETIME2(6), DATASYNC DATETIME2(6), ORDEMPRODUCAO INT, PRIMARY KEY (HANDLE))');
        $this->addSql('CREATE UNIQUE NONCLUSTERED INDEX UQ__K_PRODUC__B32894FE98938625 ON K_PRODUCAOETAPAS (ORDEMPRODUCAO) WHERE ORDEMPRODUCAO IS NOT NULL');
        $this->addSql('CREATE TABLE K_PRODUCAOITENS (HANDLE INT NOT NULL, NOTAITENS INT, DATAPRAZOORIGINAL DATE, DATAPRAZOREAL DATE, DATACADASTRO DATE, DATAAUT DATETIME2(6), DATASYNC DATETIME2(6), STATUS INT, FILIAL INT, NOTAS NVARCHAR(255) COLLATE Latin1_General_CI_AS, CODIGOBARRAS NVARCHAR(10) COLLATE Latin1_General_CI_AS, PRIMARY KEY (HANDLE))');
        $this->addSql('CREATE TABLE K_PRODUCAOTERMINAL (HANDLE INT NOT NULL, NOME NVARCHAR(50) COLLATE Latin1_General_CI_AS, PRODUCAOETAPAS INT, DATAAUT DATETIME2(6), DATASYNC DATETIME2(6), ATIVO NCHAR(1) COLLATE Latin1_General_CI_AS, PRIMARY KEY (HANDLE))');
        $this->addSql('CREATE TABLE K_USUARIOSNIVEIS (HANDLE INT NOT NULL, NOME NVARCHAR(15) COLLATE Latin1_General_CI_AS, DATAAUT DATETIME2(6), DATASYNC DATETIME2(6), DESCRICAO NVARCHAR(50) COLLATE Latin1_General_CI_AS, PORCENTAGEM DOUBLE PRECISION, PRIMARY KEY (HANDLE))');
        $this->addSql('DROP TABLE clube');
        $this->addSql('DROP TABLE pessoa');
        $this->addSql('DROP TABLE liga');
        $this->addSql('ALTER TABLE todocartoes ALTER COLUMN posicao INT NOT NULL');
        $this->addSql('ALTER TABLE todocartoes ADD CONSTRAINT DF_81609045_9B80C31A DEFAULT 1 FOR posicao');
        $this->addSql('ALTER TABLE todocartoes ALTER COLUMN is_active BIT NOT NULL');
        $this->addSql('ALTER TABLE todocartoes ADD CONSTRAINT DF_81609045_1B5771DD DEFAULT \'0\' FOR is_active');
        $this->addSql('ALTER TABLE todolistas ALTER COLUMN posicao INT NOT NULL');
        $this->addSql('ALTER TABLE todolistas ADD CONSTRAINT DF_C221FE2F_9B80C31A DEFAULT 1 FOR posicao');
    }
}
